/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TiptekRouteImport } from './routes/tiptek'
import { Route as TokenRouteImport } from './routes/token'
import { Route as ApiPublicHooksProcessTelegramUpdatesRouteImport } from './routes/api/public/hooks/process-telegram-updates'
import { Route as ApiPublicHooksRefreshCallsRouteImport } from './routes/api/public/hooks/refresh-calls'
import { Route as ApiPublicHooksVerifyTipsRouteImport } from './routes/api/public/hooks/verify-tips'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TiptekRoute = TiptekRouteImport.update({
  id: '/tiptek',
  path: '/tiptek',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessTelegramUpdatesRoute =
  ApiPublicHooksProcessTelegramUpdatesRouteImport.update({
    id: '/api/public/hooks/process-telegram-updates',
    path: '/api/public/hooks/process-telegram-updates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshCallsRoute =
  ApiPublicHooksRefreshCallsRouteImport.update({
    id: '/api/public/hooks/refresh-calls',
    path: '/api/public/hooks/refresh-calls',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVerifyTipsRoute =
  ApiPublicHooksVerifyTipsRouteImport.update({
    id: '/api/public/hooks/verify-tips',
    path: '/api/public/hooks/verify-tips',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/brand': typeof BrandRoute
  '/groups': typeof GroupsRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/tiptek': typeof TiptekRoute
  '/token': typeof TokenRoute
  '/api/public/hooks/process-telegram-updates': typeof ApiPublicHooksProcessTelegramUpdatesRoute
  '/api/public/hooks/refresh-calls': typeof ApiPublicHooksRefreshCallsRoute
  '/api/public/hooks/verify-tips': typeof ApiPublicHooksVerifyTipsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/brand': typeof BrandRoute
  '/groups': typeof GroupsRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/tiptek': typeof TiptekRoute
  '/token': typeof TokenRoute
  '/api/public/hooks/process-telegram-updates': typeof ApiPublicHooksProcessTelegramUpdatesRoute
  '/api/public/hooks/refresh-calls': typeof ApiPublicHooksRefreshCallsRoute
  '/api/public/hooks/verify-tips': typeof ApiPublicHooksVerifyTipsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/brand': typeof BrandRoute
  '/groups': typeof GroupsRoute
  '/privacy': typeof PrivacyRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/tiptek': typeof TiptekRoute
  '/token': typeof TokenRoute
  '/api/public/hooks/process-telegram-updates': typeof ApiPublicHooksProcessTelegramUpdatesRoute
  '/api/public/hooks/refresh-calls': typeof ApiPublicHooksRefreshCallsRoute
  '/api/public/hooks/verify-tips': typeof ApiPublicHooksVerifyTipsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/brand'
    | '/groups'
    | '/privacy'
    | '/risk'
    | '/terms'
    | '/tiptek'
    | '/token'
    | '/api/public/hooks/process-telegram-updates'
    | '/api/public/hooks/refresh-calls'
    | '/api/public/hooks/verify-tips'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/brand'
    | '/groups'
    | '/privacy'
    | '/risk'
    | '/terms'
    | '/tiptek'
    | '/token'
    | '/api/public/hooks/process-telegram-updates'
    | '/api/public/hooks/refresh-calls'
    | '/api/public/hooks/verify-tips'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/brand'
    | '/groups'
    | '/privacy'
    | '/risk'
    | '/terms'
    | '/tiptek'
    | '/token'
    | '/api/public/hooks/process-telegram-updates'
    | '/api/public/hooks/refresh-calls'
    | '/api/public/hooks/verify-tips'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BrandRoute: typeof BrandRoute
  GroupsRoute: typeof GroupsRoute
  PrivacyRoute: typeof PrivacyRoute
  RiskRoute: typeof RiskRoute
  TermsRoute: typeof TermsRoute
  TiptekRoute: typeof TiptekRoute
  TokenRoute: typeof TokenRoute
  ApiPublicHooksProcessTelegramUpdatesRoute: typeof ApiPublicHooksProcessTelegramUpdatesRoute
  ApiPublicHooksRefreshCallsRoute: typeof ApiPublicHooksRefreshCallsRoute
  ApiPublicHooksVerifyTipsRoute: typeof ApiPublicHooksVerifyTipsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiptek': {
      id: '/tiptek'
      path: '/tiptek'
      fullPath: '/tiptek'
      preLoaderRoute: typeof TiptekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-telegram-updates': {
      id: '/api/public/hooks/process-telegram-updates'
      path: '/api/public/hooks/process-telegram-updates'
      fullPath: '/api/public/hooks/process-telegram-updates'
      preLoaderRoute: typeof ApiPublicHooksProcessTelegramUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-calls': {
      id: '/api/public/hooks/refresh-calls'
      path: '/api/public/hooks/refresh-calls'
      fullPath: '/api/public/hooks/refresh-calls'
      preLoaderRoute: typeof ApiPublicHooksRefreshCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verify-tips': {
      id: '/api/public/hooks/verify-tips'
      path: '/api/public/hooks/verify-tips'
      fullPath: '/api/public/hooks/verify-tips'
      preLoaderRoute: typeof ApiPublicHooksVerifyTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BrandRoute: BrandRoute,
  GroupsRoute: GroupsRoute,
  PrivacyRoute: PrivacyRoute,
  RiskRoute: RiskRoute,
  TermsRoute: TermsRoute,
  TiptekRoute: TiptekRoute,
  TokenRoute: TokenRoute,
  ApiPublicHooksProcessTelegramUpdatesRoute:
    ApiPublicHooksProcessTelegramUpdatesRoute,
  ApiPublicHooksRefreshCallsRoute: ApiPublicHooksRefreshCallsRoute,
  ApiPublicHooksVerifyTipsRoute: ApiPublicHooksVerifyTipsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
