/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiPublicHooksRefreshCallsRouteImport } from './routes/api/public/hooks/refresh-calls'
import { Route as ApiPublicHooksVerifyTipsRouteImport } from './routes/api/public/hooks/verify-tips'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshCallsRoute =
  ApiPublicHooksRefreshCallsRouteImport.update({
    id: '/api/public/hooks/refresh-calls',
    path: '/api/public/hooks/refresh-calls',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVerifyTipsRoute =
  ApiPublicHooksVerifyTipsRouteImport.update({
    id: '/api/public/hooks/verify-tips',
    path: '/api/public/hooks/verify-tips',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/public/hooks/refresh-calls': typeof ApiPublicHooksRefreshCallsRoute
  '/api/public/hooks/verify-tips': typeof ApiPublicHooksVerifyTipsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/public/hooks/refresh-calls': typeof ApiPublicHooksRefreshCallsRoute
  '/api/public/hooks/verify-tips': typeof ApiPublicHooksVerifyTipsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/public/hooks/refresh-calls': typeof ApiPublicHooksRefreshCallsRoute
  '/api/public/hooks/verify-tips': typeof ApiPublicHooksVerifyTipsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/public/hooks/refresh-calls'
    | '/api/public/hooks/verify-tips'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/public/hooks/refresh-calls'
    | '/api/public/hooks/verify-tips'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/public/hooks/refresh-calls'
    | '/api/public/hooks/verify-tips'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ApiPublicHooksRefreshCallsRoute: typeof ApiPublicHooksRefreshCallsRoute
  ApiPublicHooksVerifyTipsRoute: typeof ApiPublicHooksVerifyTipsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-calls': {
      id: '/api/public/hooks/refresh-calls'
      path: '/api/public/hooks/refresh-calls'
      fullPath: '/api/public/hooks/refresh-calls'
      preLoaderRoute: typeof ApiPublicHooksRefreshCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/verify-tips': {
      id: '/api/public/hooks/verify-tips'
      path: '/api/public/hooks/verify-tips'
      fullPath: '/api/public/hooks/verify-tips'
      preLoaderRoute: typeof ApiPublicHooksVerifyTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ApiPublicHooksRefreshCallsRoute: ApiPublicHooksRefreshCallsRoute,
  ApiPublicHooksVerifyTipsRoute: ApiPublicHooksVerifyTipsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
